version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    command: ["--root", "/srv", "--baseurl", "/filebrowser"]
    volumes:
      - ./files:/srv
    expose:
      - "80"
    networks:
      - web

  minio_service:
    image: minio/minio:latest
    container_name: minio_service
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:50020/minio-console
    volumes:
      - ./minio/minio_data:/data
    ports:
      - "50021:9000"  # API مستقیم برای mc / AWS clients
      - "50022:9001"  # Console مستقیم
    networks:
      - web

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "50020:50020"   # برای reverse proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - filebrowser
      - minio_service
    networks:
      - web

networks:
  web:
    driver: bridge

