version: '3.9'

services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
    container_name: fastapi_service
    working_dir: /app
    volumes:
      - ./fastapi_app:/app
    expose:
      - "8000"

  minio:
    image: quay.io/minio/minio
    container_name: minio_service
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:1000/minio-console
    volumes:
      - ./minio/minio_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "1000:1000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi
      - minio
