services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./files:/srv
      - ./filebrowser.db:/database/filebrowser.db
    expose:
      - "8080"
    networks:
      - web

  minio:
    image: quay.io/minio/minio
    container_name: minio_service
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:1000/minio-console
    volumes:
      - ./minio/minio_data:/data
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "1000:1000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - filebrowser
      - minio
    networks:
      - web

networks:
  web:
    driver: bridge

